import Nav from "./(components)/Nav"
import "./globals.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="ml-64 p-8">
        <Nav />
        {children}
      </body>
    </html>
  )
}
